<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Paddock.Domain\Paddock.Domain.csproj" />
    <ProjectReference Include="..\..\src\Paddock.Data\Paddock.Data.csproj" />
    <ProjectReference Include="..\..\src\Paddock.Persistence\Paddock.Persistence.csproj" />
    <ProjectReference Include="..\..\tools\Paddock.DataPipeline\Paddock.DataPipeline.csproj" />
    <ProjectReference Include="..\..\tools\Paddock.SimRunner\Paddock.SimRunner.csproj" />
  </ItemGroup>
</Project>
