<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Paddock.Application\Paddock.Application.csproj" />
    <ProjectReference Include="..\..\src\Paddock.Data\Paddock.Data.csproj" />
  </ItemGroup>
</Project>
