<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Paddock.Application\Paddock.Application.csproj" />
    <ProjectReference Include="..\Paddock.Data\Paddock.Data.csproj" />
    <ProjectReference Include="..\Paddock.Persistence\Paddock.Persistence.csproj" />
    <ProjectReference Include="..\..\tools\Paddock.SimRunner\Paddock.SimRunner.csproj" />
    <PackageReference Include="Photino.NET" />
  </ItemGroup>
</Project>
