// Generated by tools/Paddock.TypeGen. Do not edit.
// Dates are ISO strings. JSON numbers that end in Cents are integer cents.

export type IsoDate = string;

export type BoardForecastKind = "Unknown" | "Protected" | "Safe" | "AtRisk";

export type ForecastKind = "Unknown" | "OnTrack" | "OffTrack" | "NotProjectable";

export type InboxStatus = "Open" | "Resolved" | "Dismissed" | "Expired";

export type JuniorProgramme = "CheapSlow" | "ExpensiveFast";

export type NegotiationStatus = "Open" | "AwaitingResponse" | "Countered" | "PersonAgreed" | "Considering" | "Agreed" | "Refused" | "WalkedAway" | "Lost" | "Lapsed";

export type NegotiationSubjectKind = "DriverSeat" | "StaffRole";

export type ObjectiveStatus = "Open" | "Met" | "Failed" | "Withdrawn";

export type OptionHolder = "Team" | "Person";

export type PrincipalKind = "Human" | "Ai";

export type RoundKind = "Offer" | "Counter" | "Acceptance" | "Refusal";

export type ScoutFocusKind = "Pool" | "Person";

export type SeatStatus = "NumberOne" | "Equal" | "NumberTwo" | "Reserve";

export type StaffRole = "TechnicalDirector" | "ChiefDesigner" | "EngineDesigner" | "HeadOfAerodynamics" | "HeadOfVehicleDynamics" | "RaceEngineer" | "Strategist" | "ChiefMechanic" | "Scout" | "CommercialDirector" | "TeamPrincipal";

export type SupplyDealStatus = "Active" | "Ended" | "Voided";

export type SupplyItem = "Engine" | "Tyres" | "Fuel";

export type SupplyKind = "Works" | "Partner" | "Customer" | "LastYearEngine";

export interface AdvanceDayView {
  date: string;
}

export interface BeginSponsorCall {
  managerId: string;
  organizationId: string;
  slot: number;
  sponsorId: string;
}

export interface BoardForecastView {
  kind: BoardForecastKind;
  message: TranslationMessage;
  reviewsLeft: number | null;
}

export interface BoardStateView {
  band: TranslationMessage;
  confidence: number;
  "protected": boolean;
  protectedUntil: IsoDate | null;
  reviewsBelowBar: number;
  reviewsToDismiss: number;
}

export interface BoardView {
  boards: DeveloperBoardLine[];
  observer: ObserverView | null;
  own: OwnBoardView | null;
  reputation: ReputationView | null;
}

export interface BoardWhyView {
  currentPosition: number | null;
  expectations: ObjectiveItemView[];
  expectedPosition: number | null;
  history: ObjectiveItemView[];
  targetConfidence: number | null;
}

export interface BookTestCall {
  managerId: string;
  organizationId: string;
}

export interface CalendarRoundView {
  circuitId: string;
  circuitName: string;
  country: string;
  finished: boolean;
  layoutId: string;
  practice: string | null;
  qualifying: string | null;
  race: string | null;
  round: number;
  season: number;
}

export interface CalendarView {
  rounds: CalendarRoundView[];
  season: number;
}

export interface CancelTestCall {
  managerId: string;
  organizationId: string;
  testOn: string;
}

export interface CarBandView {
  high: number;
  low: number;
}

export interface CareerSavedView {
  hash: string;
  name: string;
}

export interface CareerStartedView {
  date: string;
  hash: string;
  managerId: string;
  organizationId: string;
  peopleNoticeKey: string | null;
}

export interface CommandAck {
  accepted: boolean;
}

export interface CommitConceptCall {
  managerId: string;
  organizationId: string;
  projectId: string;
}

export interface DeveloperBoardLine {
  archetype: string;
  confidenceTenths: number;
  kind: PrincipalKind | null;
  lowStreak: number;
  organizationId: string;
  patience: number;
  principal: string | null;
}

export interface DevelopmentForecast {
  braking: CarBandView;
  downforce: CarBandView;
  mechanicalGrip: CarBandView;
  reliability: CarBandView;
  until: IsoDate;
}

export interface DevelopmentOverview {
  own: OwnDevelopmentView[];
}

export interface DevelopmentSplitCall {
  accountPercent: number;
  aeroPriority: number;
  chassisPriority: number;
  currentPercent: number;
  managerId: string;
  nextYearPercent: number;
  organizationId: string;
  reliabilityPriority: number;
  tyresPriority: number;
}

export interface DismissInboxCall {
  itemId: string;
  managerId: string;
}

export interface DriverCall {
  managerId: string;
  personId: string;
}

export interface DriverContractView {
  contractId: string;
  end: string;
  optionDeadline: string | null;
  optionYears: number | null;
  releaseAmount: number | null;
  salary: number;
  seat: string;
  start: string;
}

export interface DriverProfileView {
  age: number;
  attributes: KnownAttributeView[];
  contract: DriverContractView | null;
  contractEnd: string | null;
  found: boolean;
  freeAgent: boolean;
  name: string;
  nationality: string;
  organizationId: string | null;
  organizationName: string | null;
  own: boolean;
  personId: string;
  potential: KnownAttributeView | null;
  seasons: DriverSeasonView[];
  seat: string | null;
}

export interface DriverSeasonView {
  best: number | null;
  podiums: number;
  retirements: number;
  season: number;
  starts: number;
  teamId: string;
  teamName: string;
  wins: number;
}

export interface DriversView {
  market: MarketDriverView[];
  own: OwnDriverView[];
}

export interface ExitClause {
  positionWorseThan: number;
}

export interface FinanceViewOwn {
  cashCents: number;
  certainIncomeCents: number;
  forecastCashCents: number;
  forecastNote: TranslationMessage;
  ledger: LedgerLineView[];
  loanOffers: number;
  obligationsCents: number;
}

export interface FinanceViewUnknown {
  reason: TranslationMessage;
}

export interface FundJuniorCall {
  managerId: string;
  personHandle: string;
  programme: string;
}

export interface InboxItemView {
  chosenOptionId: string | null;
  closedOn: IsoDate | null;
  created: IsoDate;
  defaultOptionId: string | null;
  id: string;
  kind: string;
  managerId: string;
  needsDecision: boolean;
  options: InboxOptionView[];
  status: InboxStatus;
  subject: TranslationMessage;
  validUntil: IsoDate | null;
}

export interface InboxOptionView {
  consequence: TranslationMessage;
  id: string;
  isDefault: boolean;
  label: TranslationMessage;
}

export interface InboxView {
  items: InboxItemView[];
  openCount: number;
  openDecisionCount: number;
}

export interface InfrastructureOverview {
  own: OwnInfrastructureView[];
}

export interface KnownAttributeView {
  high: number;
  key: string;
  low: number;
}

export interface LedgerLineView {
  amountCents: number;
  category: string;
  on: IsoDate;
  reason: TranslationMessage;
}

export interface LiveCarFramesView {
  carId: string;
  distanceM: number[];
  inPit: boolean[];
  pitM: number[];
  speedMps: number[];
  timeMs: number[];
}

export interface LiveCarView {
  carId: string;
  driverName: string;
  grid: number | null;
  nationality: string;
  own: boolean;
  shortName: string;
  teamId: string;
  teamName: string;
}

export interface LiveClockView {
  active: boolean;
  durationMs: number;
  finished: boolean;
  paused: boolean;
  raceTimeMs: number;
  round: number;
  season: number;
  speed: number;
  speeds: number[];
}

export interface LiveEventView {
  args: ReportArgView[];
  carId: string | null;
  durationMs: number | null;
  gapMs: number | null;
  key: string | null;
  kind: string;
  lap: number;
  lapTimeMs: number | null;
  others: string[];
  own: boolean;
  position: number | null;
  seq: number;
  timeMs: number;
  tyres: string | null;
}

export interface LiveFramesCall {
  fromMs: number;
  managerId: string;
  toMs: number;
}

export interface LiveFramesView {
  cars: LiveCarFramesView[];
  found: boolean;
  fromMs: number;
  toMs: number;
}

export interface LiveRaceControlCall {
  action: string;
  managerId: string;
  speed: number | null;
}

export interface LiveRaceView {
  cars: LiveCarView[];
  circuitName: string | null;
  country: string | null;
  durationMs: number;
  events: LiveEventView[];
  found: boolean;
  framesApproximate: boolean;
  lapLengthM: number;
  layoutId: string | null;
  round: number;
  season: number;
  startAirC: string | null;
  startCondition: string | null;
  strategy: LiveStrategyView;
  totalLaps: number;
}

export interface LiveStrategyView {
  strategistId: string | null;
  strategistName: string | null;
}

export interface LoadCareerCall {
  managerId: string;
  path: string;
}

export interface LogisticsView {
  circuitCountry: string | null;
  costCents: number;
  days: number;
  mode: string;
}

export interface ManagerCall {
  managerId: string;
}

export interface ManagerCarRoster {
  own: OwnCarView[];
  rivals: RivalCarView[];
}

export interface ManagerProfileView {
  age: number;
  attributes: KnownAttributeView[];
  found: boolean;
  name: string;
  nationality: string;
  personId: string;
  since: string | null;
}

export interface ManagerSupplyView {
  deals: OwnSupplyDealView[];
  talks: OwnSupplyTalkView[];
}

export interface MarketDriverView {
  freeSince: string | null;
  name: string;
  nationality: string;
  personId: string;
}

export interface MarketPersonView {
  age: number;
  attributes: KnownAttributeView[];
  contractEnd: string | null;
  freeAgent: boolean;
  name: string;
  nationality: string;
  organizationId: string | null;
  organizationName: string | null;
  personId: string;
  seat: string | null;
}

export interface MarketView {
  contracted: MarketPersonView[];
  freeAgents: MarketPersonView[];
}

export interface NegotiationIdCall {
  managerId: string;
  negotiationId: string;
}

export interface NegotiationRoundView {
  kind: RoundKind;
  "number": number;
  on: IsoDate;
  reasons: TranslationMessage[];
  terms: OfferTerms | null;
}

export interface NegotiationSubjectView {
  key: string;
  kind: NegotiationSubjectKind;
  staffRole: StaffRole | null;
}

export interface NegotiationView {
  counter: OfferTerms | null;
  deadline: IsoDate;
  history: NegotiationRoundView[];
  id: string;
  interest: TranslationMessage;
  knownAttributes: KnownAttributeView[];
  managerId: string;
  maxRounds: number;
  nationality: string;
  offer: OfferTerms | null;
  opened: IsoDate;
  person: string;
  personName: string;
  proposer: string;
  reasons: TranslationMessage[];
  respondOn: IsoDate | null;
  roundsUsed: number;
  signedContract: string | null;
  status: NegotiationStatus;
  statusText: TranslationMessage;
  subject: NegotiationSubjectView;
}

export interface NegotiationsView {
  items: NegotiationView[];
}

export interface NewCareerCall {
  ai: string | null;
  familyName: string;
  fatality: string | null;
  givenName: string;
  history: number | null;
  managerId: string;
  name: string | null;
  nationality: string;
  noNumbers: boolean | null;
  people: string | null;
  preset: string | null;
  randomness: number | null;
  rules: string | null;
  seed: number | null;
  teamId: string;
  tilt: string;
  year: number | null;
}

export interface NextRaceView {
  circuitId: string | null;
  circuitName: string | null;
  country: string | null;
  date: string | null;
  layoutId: string | null;
  round: number | null;
  season: number | null;
}

export interface ObjectiveForecastView {
  kind: ForecastKind;
  message: TranslationMessage;
  projected: number | null;
}

export interface ObjectiveItemView {
  deadline: IsoDate;
  forecast: ObjectiveForecastView | null;
  id: string;
  onFailed: TranslationMessage;
  onMet: TranslationMessage;
  ownerId: string;
  requirement: TranslationMessage;
  state: ObjectiveStateView;
  title: TranslationMessage;
  why: ObjectiveWhyView;
}

export interface ObjectiveStateView {
  current: number | null;
  daysLeft: number;
  holds: boolean | null;
  status: ObjectiveStatus;
  target: number | null;
}

export interface ObjectiveWhyView {
  grantorId: string;
  reason: TranslationMessage;
}

export interface ObserverView {
  openOffers: number;
  since: IsoDate;
  status: TranslationMessage;
}

export interface OfferOption {
  extraYears: number;
  holder: OptionHolder;
}

export interface OfferTerms {
  exit: ExitClause | null;
  option: OfferOption | null;
  pointsBonus: number;
  salary: number;
  seat: SeatStatus | null;
  titleBonus: number;
  winBonus: number;
  years: number;
}

export interface OpenNegotiationCall {
  deadline: string | null;
  managerId: string;
  organizationId: string;
  personId: string;
  subject: string;
}

export interface OwnBoardView {
  forecast: BoardForecastView;
  organizationId: string;
  state: BoardStateView;
  why: BoardWhyView;
}

export interface OwnCarView {
  aeroMilli: number;
  braking: CarBandView;
  carId: string;
  ceiling: CarBandView;
  coolingMilli: number;
  downforce: CarBandView;
  integrationMilli: number;
  mechanicalGrip: CarBandView;
  philosophyMilli: number;
  power: CarBandView;
  reliability: CarBandView;
  season: number;
  tyreMilli: number;
  understanding: CarBandView;
  windowMilli: number;
}

export interface OwnDevelopmentView {
  account: CarBandView;
  accountPercent: number;
  aeroPriority: number;
  chassisPriority: number;
  currentPercent: number;
  daysToNextRace: number | null;
  forecast: DevelopmentForecast;
  headcount: number;
  nextYearPercent: number;
  ongoingGain: CarBandView;
  organizationId: string;
  projects: OwnProjectView[];
  reliabilityPriority: number;
  tyresPriority: number;
}

export interface OwnDriverView {
  end: string;
  injury: string | null;
  name: string;
  nationality: string;
  personId: string;
  returnRange: string | null;
  seat: string;
}

export interface OwnEngineView {
  lagSeasons: number;
  power: CarBandView;
  reliability: CarBandView;
  versionSeason: number;
}

export interface OwnFacilityView {
  buildEnds: IsoDate | null;
  building: boolean;
  eligible: boolean;
  frontierMilli: number;
  kind: string;
  qualityMilli: number;
  relativeQuality: number;
  unlocked: boolean;
  upgradeCostCents: number;
  upgradeDays: number;
}

export interface OwnInfrastructureView {
  facilities: OwnFacilityView[];
  homeCountry: string | null;
  nextTransport: LogisticsView | null;
  organizationId: string;
  tests: TestRentalView;
}

export interface OwnProjectView {
  area: string | null;
  engineer: string;
  expectedEnd: IsoDate;
  expectedGain: CarBandView;
  goesLiveOn: IsoDate | null;
  kind: string;
  productionCostCents: number | null;
  productionDays: number | null;
  productionEnds: IsoDate | null;
  progressPercent: number;
  projectId: string;
  racesWaited: number;
  status: string;
  timing: string;
  timingRaces: number;
}

export interface OwnSupplyDealView {
  annualPriceCents: number;
  dealId: string;
  engine: OwnEngineView | null;
  exclusive: boolean;
  firstSeason: number;
  item: SupplyItem;
  kind: SupplyKind;
  lastSeason: number;
  status: SupplyDealStatus;
  supplierId: string;
}

export interface OwnSupplyTalkView {
  counterCents: number | null;
  deadline: IsoDate;
  item: SupplyItem;
  kind: SupplyKind;
  negotiationId: string;
  offerCents: number;
  reasons: string[];
  roundsLeft: number;
  status: NegotiationStatus;
  supplierId: string;
}

export interface OwnTeamView {
  cashCents: number | null;
  name: string | null;
  organizationId: string | null;
}

export interface PointsScaleView {
  constructors: string;
  countedResults: number;
  doublePointsFinale: boolean;
  fastestLap: string;
  firstQuota: number;
  positionPoints: number[];
  resultsCounting: string;
  secondQuota: number;
}

export interface PoolBandView {
  high: number;
  key: string;
  low: number;
}

export interface PoolItemView {
  age: number;
  attributes: PoolBandView[];
  familyName: string;
  givenName: string;
  handle: string;
  nationality: string;
  potential: PoolBandView | null;
  yourFunding: JuniorProgramme | null;
}

export interface PoolView {
  cheapProgrammeCostCents: number;
  fastProgrammeCostCents: number;
  focus: ScoutFocusKind | null;
  focusHandle: string | null;
  items: PoolItemView[];
}

export interface PresetView {
  ai: string;
  fatality: string;
  history: number;
  name: string;
  noNumbers: boolean;
  people: string;
  randomness: number;
  rules: string;
}

export interface QuickRaceCall {
  managerId: string;
  round: number;
  seed: number | null;
  teamId: string;
  year: number;
}

export interface QuickRaceStartedView {
  layoutId: string;
  organizationId: string;
  round: number;
  season: number;
}

export interface QuickRoundView {
  circuitName: string | null;
  country: string | null;
  date: string;
  layoutId: string;
  points: TrackPointView[];
  round: number;
}

export interface QuickRoundsCall {
  managerId: string;
  year: number;
}

export interface QuickRoundsView {
  rounds: QuickRoundView[];
  season: number;
}

export interface RaceFactDriverView {
  driverId: string;
  driverName: string;
  timeMs: number | null;
}

export interface RaceFactsView {
  distanceMeters: number;
  fastestLap: RaceFactDriverView | null;
  laps: number;
  pole: RaceFactDriverView | null;
}

export interface RaceResultCall {
  managerId: string;
  round: number | null;
  season: number | null;
}

export interface RaceResultView {
  facts: RaceFactsView | null;
  found: boolean;
  layoutId: string | null;
  round: number;
  rows: RaceRowView[];
  season: number;
  sections: ReportSectionView[];
}

export interface RaceRowView {
  classified: boolean;
  driverId: string;
  driverName: string;
  fastestLapMs: number | null;
  gapMs: number | null;
  gridPosition: number | null;
  lapsCompleted: number | null;
  lapsDown: number;
  nationality: string;
  points: string;
  position: number;
  retirementKey: string;
  teamId: string;
  teamName: string;
  timeMs: number | null;
}

export interface RenewContractCall {
  contractId: string;
  exerciseOption: boolean;
  managerId: string;
  pointsBonus: number | null;
  salary: number | null;
  seat: string | null;
  titleBonus: number | null;
  winBonus: number | null;
  years: number | null;
}

export interface ReportArgView {
  name: string;
  value: string;
}

export interface ReportLineView {
  args: ReportArgView[];
  count: number | null;
  key: string;
}

export interface ReportSectionView {
  lines: ReportLineView[];
  title: ReportLineView;
}

export interface ReputationLineView {
  on: IsoDate;
  points: number;
  reason: TranslationMessage;
}

export interface ReputationView {
  band: TranslationMessage;
  history: ReputationLineView[];
  points: number;
}

export interface ResolveInboxCall {
  itemId: string;
  managerId: string;
  optionId: string;
}

export interface RivalCarView {
  carId: string;
  organizationId: string;
}

export interface SaveCareerCall {
  managerId: string;
  name: string;
}

export interface SaveListItem {
  careerName: string;
  date: string;
  name: string;
  savedAt: string;
  teamId: string;
}

export interface SaveListView {
  saves: SaveListItem[];
}

export interface ScoutFocusCall {
  managerId: string;
  personHandle: string | null;
}

export interface SessionView {
  date: string | null;
  managerId: string;
  organizationId: string | null;
  organizationName: string | null;
  peopleNoticeKey: string | null;
  presets: PresetView[];
  started: boolean;
  suggestedSeed: string;
  suggestedYear: number;
}

export interface ShellView {
  blockingKind: string | null;
  cashCents: number | null;
  date: string;
  decisionItemId: string | null;
  decisionKind: string | null;
  decisionSubject: TranslationMessage | null;
  inboxDecisions: number;
  inboxOpen: number;
  managerId: string;
  organizationId: string | null;
  organizationName: string | null;
}

export interface SignPoolCall {
  managerId: string;
  personHandle: string;
  role: string;
}

export interface SponsorCandidateView {
  blocked: TranslationMessage | null;
  indicativeAnnualCents: number;
  industry: TranslationMessage;
  sponsorId: string;
  sponsorName: string;
}

export interface SponsorDealView {
  annualCents: number;
  end: IsoDate;
  id: string;
  industry: TranslationMessage;
  objectiveId: string | null;
  slot: TranslationMessage;
  sponsorId: string;
  sponsorName: string;
  start: IsoDate;
  trust: number;
}

export interface SponsorOfferCall {
  accept: boolean;
  managerId: string;
  offerId: string;
  organizationId: string;
}

export interface SponsorOfferView {
  annualCents: number;
  id: string;
  sponsorName: string;
  validUntil: IsoDate;
}

export interface SponsorSlotView {
  candidates: SponsorCandidateView[];
  dealId: string | null;
  kind: TranslationMessage;
  slot: number;
  talkId: string | null;
}

export interface SponsorTalkCall {
  managerId: string;
  organizationId: string;
  talkId: string;
}

export interface SponsorTalkView {
  cappedAnnualCents: number;
  currentAnnualCents: number;
  id: string;
  note: TranslationMessage;
  objective: TranslationMessage | null;
  rivalKnown: boolean | null;
  slot: TranslationMessage;
  sponsorId: string;
  sponsorName: string;
}

export interface SponsorViewOwn {
  deals: SponsorDealView[];
  objectives: ObjectiveItemView[];
  offers: SponsorOfferView[];
  slots: SponsorSlotView[];
  talks: SponsorTalkView[];
}

export interface SponsorViewUnknown {
  reason: TranslationMessage;
}

export interface StaffAttributeView {
  high: number;
  key: string;
  low: number;
}

export interface StaffListView {
  people: StaffPersonView[];
}

export interface StaffPersonView {
  age: number;
  attributes: StaffAttributeView[] | null;
  contractEnd: string | null;
  driverId: string | null;
  name: string;
  nationality: string;
  organizationId: string;
  ownTeam: boolean;
  personId: string;
  relationship: number | null;
  role: string;
}

export interface StandingRowView {
  id: string;
  name: string;
  nationality: string;
  points: string;
  position: number;
  teamId: string | null;
  teamName: string | null;
  wins: number;
}

export interface StandingsView {
  constructors: StandingRowView[];
  drivers: StandingRowView[];
  roundsCompleted: number;
  rules: PointsScaleView | null;
  season: number;
  totalRounds: number;
}

export interface SubmitOfferCall {
  exitWorseThan: number | null;
  managerId: string;
  negotiationId: string;
  optionHolder: string | null;
  optionYears: number | null;
  pointsBonus: number;
  salary: number;
  seat: string | null;
  titleBonus: number;
  winBonus: number;
  years: number;
}

export interface SupplyProposalCall {
  annualPriceCents: number;
  exclusive: boolean;
  firstSeason: number;
  item: string;
  kind: string;
  managerId: string;
  negotiationId: string | null;
  organizationId: string;
  seasons: number;
  supplierId: string;
}

export interface SupplyResponseCall {
  accept: boolean;
  managerId: string;
  negotiationId: string;
  organizationId: string;
}

export interface TeamCardDriver {
  age: number;
  name: string;
  nationality: string;
  seat: string;
}

export interface TeamCardEngine {
  name: string;
  supplier: string;
  supplyType: string;
}

export interface TeamListView {
  problem: TranslationMessage | null;
  teams: TeamOptionView[];
  year: number;
}

export interface TeamOptionView {
  budget: string | null;
  drivers: TeamCardDriver[];
  engine: TeamCardEngine | null;
  expected: number | null;
  fieldSize: number | null;
  id: string;
  lastSeason: number | null;
  name: string;
}

export interface TeamsCall {
  ai: string | null;
  fatality: string | null;
  history: number | null;
  managerId: string;
  noNumbers: boolean | null;
  people: string | null;
  preset: string | null;
  randomness: number | null;
  rules: string | null;
  seed: number | null;
  year: number;
}

export interface TestRentalView {
  allowed: boolean;
  booked: IsoDate[];
  cap: number;
  costCents: number;
  nextDate: IsoDate;
  used: number;
}

export interface TrackCall {
  layoutId: string | null;
  managerId: string;
}

export interface TrackPointView {
  x: number;
  y: number;
}

export interface TrackView {
  character: string[];
  circuitId: string | null;
  country: string | null;
  found: boolean;
  layoutId: string | null;
  lengthKm: number | null;
  name: string | null;
  points: TrackPointView[];
  races: number;
  retirements: number;
  winners: TrackWinnerView[];
}

export interface TrackWinnerView {
  driverId: string;
  driverName: string;
  round: number;
  season: number;
  teamId: string;
  teamName: string;
}

export interface TranslationMessage {
  key: string;
  parameters: Record<string, string>;
}

export interface UpgradeFacilityCall {
  kind: string;
  managerId: string;
  organizationId: string;
}

export type FinanceView = FinanceViewOwn | FinanceViewUnknown;

export type SponsorView = SponsorViewOwn | SponsorViewUnknown;

export interface BridgeQueryMap {
  shell: { args: ManagerCall; result: ShellView };
  inbox: { args: ManagerCall; result: InboxView };
  team: { args: ManagerCall; result: OwnTeamView };
  drivers: { args: ManagerCall; result: DriversView };
  cars: { args: ManagerCall; result: ManagerCarRoster };
  development: { args: ManagerCall; result: DevelopmentOverview };
  infrastructure: { args: ManagerCall; result: InfrastructureOverview };
  sponsors: { args: ManagerCall; result: SponsorView };
  finance: { args: ManagerCall; result: FinanceView };
  board: { args: ManagerCall; result: BoardView };
  pool: { args: ManagerCall; result: PoolView };
  supply: { args: ManagerCall; result: ManagerSupplyView };
  negotiations: { args: ManagerCall; result: NegotiationsView };
  session: { args: ManagerCall; result: SessionView };
  teams: { args: TeamsCall; result: TeamListView };
  saves: { args: ManagerCall; result: SaveListView };
  calendar: { args: ManagerCall; result: CalendarView };
  standings: { args: ManagerCall; result: StandingsView };
  raceResult: { args: RaceResultCall; result: RaceResultView };
  nextRace: { args: ManagerCall; result: NextRaceView };
  track: { args: TrackCall; result: TrackView };
  staff: { args: ManagerCall; result: StaffListView };
  market: { args: ManagerCall; result: MarketView };
  driver: { args: DriverCall; result: DriverProfileView };
  manager: { args: ManagerCall; result: ManagerProfileView };
  liveRace: { args: ManagerCall; result: LiveRaceView };
  liveFrames: { args: LiveFramesCall; result: LiveFramesView };
  liveClock: { args: ManagerCall; result: LiveClockView };
  quickRounds: { args: QuickRoundsCall; result: QuickRoundsView };
}

export interface BridgeCommandMap {
  advanceDay: { args: ManagerCall; result: AdvanceDayView };
  resolveInbox: { args: ResolveInboxCall; result: CommandAck };
  dismissInbox: { args: DismissInboxCall; result: CommandAck };
  newCareer: { args: NewCareerCall; result: CareerStartedView };
  loadCareer: { args: LoadCareerCall; result: CareerStartedView };
  saveCareer: { args: SaveCareerCall; result: CareerSavedView };
  openNegotiation: { args: OpenNegotiationCall; result: CommandAck };
  submitOffer: { args: SubmitOfferCall; result: CommandAck };
  acceptCounter: { args: NegotiationIdCall; result: CommandAck };
  walkAway: { args: NegotiationIdCall; result: CommandAck };
  renewContract: { args: RenewContractCall; result: CommandAck };
  beginSponsorTalks: { args: BeginSponsorCall; result: CommandAck };
  signSponsor: { args: SponsorTalkCall; result: CommandAck };
  walkAwayFromTalks: { args: SponsorTalkCall; result: CommandAck };
  respondToSponsorOffer: { args: SponsorOfferCall; result: CommandAck };
  setDevelopmentSplit: { args: DevelopmentSplitCall; result: CommandAck };
  commitConcept: { args: CommitConceptCall; result: CommandAck };
  upgradeFacility: { args: UpgradeFacilityCall; result: CommandAck };
  bookTest: { args: BookTestCall; result: CommandAck };
  cancelTest: { args: CancelTestCall; result: CommandAck };
  assignScoutFocus: { args: ScoutFocusCall; result: CommandAck };
  fundJunior: { args: FundJuniorCall; result: CommandAck };
  signPoolDriver: { args: SignPoolCall; result: CommandAck };
  proposeSupply: { args: SupplyProposalCall; result: CommandAck };
  respondToSupply: { args: SupplyResponseCall; result: CommandAck };
  liveRaceControl: { args: LiveRaceControlCall; result: LiveClockView };
  startQuickRace: { args: QuickRaceCall; result: QuickRaceStartedView };
  closeQuickRace: { args: ManagerCall; result: CommandAck };
}

export type BridgeQueryName = keyof BridgeQueryMap;

export type BridgeCommandName = keyof BridgeCommandMap;

