// Generated by tools/Paddock.TypeGen. Do not edit.
// Dates are ISO strings. JSON numbers that end in Cents are integer cents.

export type IsoDate = string;

export type BoardForecastKind = "Unknown" | "Protected" | "Safe" | "AtRisk";

export type ForecastKind = "Unknown" | "OnTrack" | "OffTrack" | "NotProjectable";

export type InboxStatus = "Open" | "Resolved" | "Dismissed" | "Expired";

export type JuniorProgramme = "CheapSlow" | "ExpensiveFast";

export type NegotiationStatus = "Open" | "AwaitingResponse" | "Countered" | "PersonAgreed" | "Considering" | "Agreed" | "Refused" | "WalkedAway" | "Lost" | "Lapsed";

export type NegotiationSubjectKind = "DriverSeat" | "StaffRole";

export type ObjectiveStatus = "Open" | "Met" | "Failed" | "Withdrawn";

export type OptionHolder = "Team" | "Person";

export type PrincipalKind = "Human" | "Ai";

export type RoundKind = "Offer" | "Counter" | "Acceptance" | "Refusal";

export type ScoutFocusKind = "Pool" | "Person";

export type SeatStatus = "NumberOne" | "Equal" | "NumberTwo" | "Reserve";

export type StaffRole = "TechnicalDirector" | "ChiefDesigner" | "EngineDesigner" | "HeadOfAerodynamics" | "HeadOfVehicleDynamics" | "RaceEngineer" | "Strategist" | "ChiefMechanic" | "Scout" | "CommercialDirector" | "TeamPrincipal";

export type SupplyDealStatus = "Active" | "Ended" | "Voided";

export type SupplyItem = "Engine" | "Tyres" | "Fuel";

export type SupplyKind = "Works" | "Partner" | "Customer" | "LastYearEngine";

export interface AdvanceDayView {
  date: string;
}

export interface BoardForecastView {
  kind: BoardForecastKind;
  message: TranslationMessage;
  reviewsLeft: number | null;
}

export interface BoardStateView {
  band: TranslationMessage;
  confidence: number;
  "protected": boolean;
  protectedUntil: IsoDate | null;
  reviewsBelowBar: number;
  reviewsToDismiss: number;
}

export interface BoardView {
  boards: DeveloperBoardLine[];
  observer: ObserverView | null;
  own: OwnBoardView | null;
  reputation: ReputationView | null;
}

export interface BoardWhyView {
  currentPosition: number | null;
  expectations: ObjectiveItemView[];
  expectedPosition: number | null;
  targetConfidence: number | null;
}

export interface CarBandView {
  high: number;
  low: number;
}

export interface CommandAck {
  accepted: boolean;
}

export interface DeveloperBoardLine {
  archetype: string;
  confidenceTenths: number;
  kind: PrincipalKind | null;
  lowStreak: number;
  organizationId: string;
  patience: number;
  principal: string | null;
}

export interface DevelopmentForecast {
  braking: CarBandView;
  downforce: CarBandView;
  mechanicalGrip: CarBandView;
  reliability: CarBandView;
  until: IsoDate;
}

export interface DevelopmentOverview {
  own: OwnDevelopmentView[];
}

export interface DismissInboxCall {
  itemId: string;
  managerId: string;
}

export interface DriversView {
  market: MarketDriverView[];
  own: OwnDriverView[];
}

export interface ExitClause {
  positionWorseThan: number;
}

export interface FinanceViewOwn {
  cashCents: number;
  certainIncomeCents: number;
  forecastCashCents: number;
  forecastNote: TranslationMessage;
  loanOffers: number;
  obligationsCents: number;
}

export interface FinanceViewUnknown {
  reason: TranslationMessage;
}

export interface InboxItemView {
  chosenOptionId: string | null;
  closedOn: IsoDate | null;
  created: IsoDate;
  defaultOptionId: string | null;
  id: string;
  kind: string;
  managerId: string;
  needsDecision: boolean;
  options: InboxOptionView[];
  status: InboxStatus;
  subject: TranslationMessage;
  validUntil: IsoDate | null;
}

export interface InboxOptionView {
  consequence: TranslationMessage;
  id: string;
  isDefault: boolean;
  label: TranslationMessage;
}

export interface InboxView {
  items: InboxItemView[];
  openCount: number;
  openDecisionCount: number;
}

export interface KnownAttributeView {
  high: number;
  key: string;
  low: number;
}

export interface ManagerCall {
  managerId: string;
}

export interface ManagerCarRoster {
  own: OwnCarView[];
  rivals: RivalCarView[];
}

export interface ManagerSupplyView {
  deals: OwnSupplyDealView[];
  talks: OwnSupplyTalkView[];
}

export interface MarketDriverView {
  freeSince: string | null;
  name: string;
  nationality: string;
  personId: string;
}

export interface NegotiationRoundView {
  kind: RoundKind;
  "number": number;
  on: IsoDate;
  reasons: TranslationMessage[];
  terms: OfferTerms | null;
}

export interface NegotiationSubject {
  key: string;
  kind: NegotiationSubjectKind;
  staffRole: StaffRole;
}

export interface NegotiationView {
  counter: OfferTerms | null;
  deadline: IsoDate;
  history: NegotiationRoundView[];
  id: string;
  interest: TranslationMessage;
  knownAttributes: KnownAttributeView[];
  managerId: string;
  maxRounds: number;
  nationality: string;
  offer: OfferTerms | null;
  opened: IsoDate;
  person: string;
  personName: string;
  proposer: string;
  reasons: TranslationMessage[];
  respondOn: IsoDate | null;
  roundsUsed: number;
  signedContract: string | null;
  status: NegotiationStatus;
  statusText: TranslationMessage;
  subject: NegotiationSubject;
}

export interface NegotiationsView {
  items: NegotiationView[];
}

export interface ObjectiveForecastView {
  kind: ForecastKind;
  message: TranslationMessage;
  projected: number | null;
}

export interface ObjectiveItemView {
  deadline: IsoDate;
  forecast: ObjectiveForecastView | null;
  id: string;
  onFailed: TranslationMessage;
  onMet: TranslationMessage;
  ownerId: string;
  requirement: TranslationMessage;
  state: ObjectiveStateView;
  title: TranslationMessage;
  why: ObjectiveWhyView;
}

export interface ObjectiveStateView {
  current: number | null;
  daysLeft: number;
  holds: boolean | null;
  status: ObjectiveStatus;
  target: number | null;
}

export interface ObjectiveWhyView {
  grantorId: string;
  reason: TranslationMessage;
}

export interface ObserverView {
  openOffers: number;
  since: IsoDate;
  status: TranslationMessage;
}

export interface OfferOption {
  extraYears: number;
  holder: OptionHolder;
}

export interface OfferTerms {
  exit: ExitClause | null;
  option: OfferOption | null;
  pointsBonus: number;
  salary: number;
  seat: SeatStatus | null;
  titleBonus: number;
  winBonus: number;
  years: number;
}

export interface OwnBoardView {
  forecast: BoardForecastView;
  organizationId: string;
  state: BoardStateView;
  why: BoardWhyView;
}

export interface OwnCarView {
  aeroMilli: number;
  braking: CarBandView;
  carId: string;
  ceiling: CarBandView;
  coolingMilli: number;
  downforce: CarBandView;
  integrationMilli: number;
  mechanicalGrip: CarBandView;
  philosophyMilli: number;
  power: CarBandView;
  reliability: CarBandView;
  season: number;
  tyreMilli: number;
  understanding: CarBandView;
  windowMilli: number;
}

export interface OwnDevelopmentView {
  account: CarBandView;
  accountPercent: number;
  aeroPriority: number;
  chassisPriority: number;
  currentPercent: number;
  daysToNextRace: number | null;
  forecast: DevelopmentForecast;
  headcount: number;
  nextYearPercent: number;
  ongoingGain: CarBandView;
  organizationId: string;
  projects: OwnProjectView[];
  reliabilityPriority: number;
  tyresPriority: number;
}

export interface OwnDriverView {
  end: string;
  name: string;
  nationality: string;
  personId: string;
  seat: string;
}

export interface OwnEngineView {
  lagSeasons: number;
  power: CarBandView;
  reliability: CarBandView;
  versionSeason: number;
}

export interface OwnProjectView {
  area: string | null;
  engineer: string;
  expectedEnd: IsoDate;
  expectedGain: CarBandView;
  goesLiveOn: IsoDate | null;
  kind: string;
  productionCostCents: number | null;
  productionDays: number | null;
  productionEnds: IsoDate | null;
  progressPercent: number;
  projectId: string;
  racesWaited: number;
  status: string;
  timing: string;
  timingRaces: number;
}

export interface OwnSupplyDealView {
  annualPriceCents: number;
  dealId: string;
  engine: OwnEngineView | null;
  exclusive: boolean;
  firstSeason: number;
  item: SupplyItem;
  kind: SupplyKind;
  lastSeason: number;
  status: SupplyDealStatus;
  supplierId: string;
}

export interface OwnSupplyTalkView {
  counterCents: number | null;
  deadline: IsoDate;
  item: SupplyItem;
  kind: SupplyKind;
  negotiationId: string;
  offerCents: number;
  reasons: string[];
  roundsLeft: number;
  status: NegotiationStatus;
  supplierId: string;
}

export interface OwnTeamView {
  cashCents: number | null;
  name: string | null;
  organizationId: string | null;
}

export interface PoolBandView {
  high: number;
  key: string;
  low: number;
}

export interface PoolItemView {
  age: number;
  attributes: PoolBandView[];
  familyName: string;
  givenName: string;
  handle: string;
  nationality: string;
  potential: PoolBandView | null;
  yourFunding: JuniorProgramme | null;
}

export interface PoolView {
  focus: ScoutFocusKind | null;
  focusHandle: string | null;
  items: PoolItemView[];
}

export interface ReputationLineView {
  on: IsoDate;
  points: number;
  reason: TranslationMessage;
}

export interface ReputationView {
  band: TranslationMessage;
  history: ReputationLineView[];
  points: number;
}

export interface ResolveInboxCall {
  itemId: string;
  managerId: string;
  optionId: string;
}

export interface RivalCarView {
  carId: string;
  organizationId: string;
}

export interface ShellView {
  blockingKind: string | null;
  cashCents: number | null;
  date: string;
  decisionItemId: string | null;
  decisionSubjectKey: string | null;
  inboxDecisions: number;
  inboxOpen: number;
  managerId: string;
  organizationId: string | null;
  organizationName: string | null;
}

export interface SponsorCandidateView {
  blocked: TranslationMessage | null;
  indicativeAnnualCents: number;
  industry: TranslationMessage;
  sponsorId: string;
  sponsorName: string;
}

export interface SponsorDealView {
  annualCents: number;
  end: IsoDate;
  id: string;
  industry: TranslationMessage;
  objectiveId: string | null;
  slot: TranslationMessage;
  sponsorId: string;
  sponsorName: string;
  start: IsoDate;
  trust: number;
}

export interface SponsorOfferView {
  annualCents: number;
  id: string;
  sponsorName: string;
  validUntil: IsoDate;
}

export interface SponsorSlotView {
  candidates: SponsorCandidateView[];
  dealId: string | null;
  kind: TranslationMessage;
  slot: number;
  talkId: string | null;
}

export interface SponsorTalkView {
  cappedAnnualCents: number;
  currentAnnualCents: number;
  id: string;
  note: TranslationMessage;
  objective: TranslationMessage | null;
  rivalKnown: boolean | null;
  slot: TranslationMessage;
  sponsorId: string;
  sponsorName: string;
}

export interface SponsorViewOwn {
  deals: SponsorDealView[];
  objectives: ObjectiveItemView[];
  offers: SponsorOfferView[];
  slots: SponsorSlotView[];
  talks: SponsorTalkView[];
}

export interface SponsorViewUnknown {
  reason: TranslationMessage;
}

export interface TranslationMessage {
  key: string;
  parameters: Record<string, string>;
}

export type FinanceView = FinanceViewOwn | FinanceViewUnknown;

export type SponsorView = SponsorViewOwn | SponsorViewUnknown;

export interface BridgeQueryMap {
  shell: { args: ManagerCall; result: ShellView };
  inbox: { args: ManagerCall; result: InboxView };
  team: { args: ManagerCall; result: OwnTeamView };
  drivers: { args: ManagerCall; result: DriversView };
  cars: { args: ManagerCall; result: ManagerCarRoster };
  development: { args: ManagerCall; result: DevelopmentOverview };
  sponsors: { args: ManagerCall; result: SponsorView };
  finance: { args: ManagerCall; result: FinanceView };
  board: { args: ManagerCall; result: BoardView };
  pool: { args: ManagerCall; result: PoolView };
  supply: { args: ManagerCall; result: ManagerSupplyView };
  negotiations: { args: ManagerCall; result: NegotiationsView };
}

export interface BridgeCommandMap {
  advanceDay: { args: ManagerCall; result: AdvanceDayView };
  resolveInbox: { args: ResolveInboxCall; result: CommandAck };
  dismissInbox: { args: DismissInboxCall; result: CommandAck };
}

export type BridgeQueryName = keyof BridgeQueryMap;

export type BridgeCommandName = keyof BridgeCommandMap;

