<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Paddock.Application\Paddock.Application.csproj" />
    <ProjectReference Include="..\Paddock.Data\Paddock.Data.csproj" />
    <ProjectReference Include="..\Paddock.Persistence\Paddock.Persistence.csproj" />
  </ItemGroup>
</Project>
