using System.Reflection;
using System.Text;
using System.Text.Json.Serialization;
using Paddock.Application.Access;
using Paddock.Application.Commands;
using Paddock.Desktop.Bridge;
using Paddock.Domain.Time;

namespace Paddock.TypeGen;

/// <summary>
/// Writes the TypeScript shape of <see cref="BridgeRegistry"/>. The rules match <see cref="BridgeValues"/>:
/// ISO dates, enum names, id values as strings, integer money left as a JSON number.
/// </summary>
public static class TypeGenerator
{
    private static readonly NullabilityInfoContext Nullability = new();

    public static string RepositoryRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "strings", "en.json"))
                && Directory.Exists(Path.Combine(dir.FullName, "data", "authored")))
            {
                return dir.FullName;
            }

            dir = dir.Parent;
        }

        throw new InvalidOperationException("Could not find the repository root from " + AppContext.BaseDirectory + ".");
    }

    public static string Generate()
    {
        var pending = new Queue<Type>();
        var seen = new HashSet<Type>();
        foreach (var endpoint in BridgeRegistry.Endpoints)
        {
            Enqueue(endpoint.ArgumentType, pending, seen);
            Enqueue(endpoint.ResultType, pending, seen);
        }

        var enums = new List<Type>();
        var objects = new List<Type>();
        var unions = new List<Type>();
        while (pending.Count > 0)
        {
            var type = pending.Dequeue();
            if (IsLeaf(type))
            {
                continue;
            }

            if (type.IsEnum)
            {
                enums.Add(type);
                continue;
            }

            if (type.IsAbstract)
            {
                unions.Add(type);
                foreach (var derived in Derived(type))
                {
                    Enqueue(derived, pending, seen);
                }

                continue;
            }

            objects.Add(type);
            foreach (var property in Properties(type))
            {
                Enqueue(Unwrap(property.PropertyType), pending, seen);
            }
        }

        var names = Names(enums.Concat(objects).Concat(unions));
        var builder = new StringBuilder();
        builder.AppendLine("// Generated by tools/Paddock.TypeGen. Do not edit.");
        builder.AppendLine("// Dates are ISO strings. JSON numbers that end in Cents are integer cents.");
        builder.AppendLine();
        builder.AppendLine("export type IsoDate = string;");
        builder.AppendLine();
        foreach (var type in enums.OrderBy(type => names[type], StringComparer.Ordinal))
        {
            builder.Append("export type ").Append(names[type]).Append(" = ");
            builder.Append(string.Join(" | ", Enum.GetNames(type).Select(name => "\"" + name + "\"")));
            builder.AppendLine(";");
            builder.AppendLine();
        }

        foreach (var type in objects.OrderBy(type => names[type], StringComparer.Ordinal))
        {
            builder.Append("export interface ").Append(names[type]).AppendLine(" {");
            foreach (var property in Properties(type))
            {
                builder.Append("  ").Append(PropertyName(Camel(property.Name))).Append(": ");
                builder.Append(Render(Unwrap(property.PropertyType), names));
                if (IsNullable(property))
                {
                    builder.Append(" | null");
                }

                builder.AppendLine(";");
            }

            builder.AppendLine("}");
            builder.AppendLine();
        }

        foreach (var type in unions.OrderBy(type => names[type], StringComparer.Ordinal))
        {
            var derived = Derived(type).Select(item => names[item]).OrderBy(name => name, StringComparer.Ordinal).ToArray();
            if (derived.Length == 0)
            {
                throw new InvalidOperationException(type.FullName + " has no concrete bridge shape.");
            }

            builder.Append("export type ").Append(names[type]).Append(" = ").Append(string.Join(" | ", derived)).AppendLine(";");
            builder.AppendLine();
        }

        builder.AppendLine("export interface BridgeQueryMap {");
        foreach (var endpoint in BridgeRegistry.Endpoints.Where(item => item.Kind == BridgeRegistry.Query))
        {
            builder.Append("  ").Append(endpoint.Name).Append(": { args: ").Append(names[endpoint.ArgumentType]);
            builder.Append("; result: ").Append(names[endpoint.ResultType]).AppendLine(" };");
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("export interface BridgeCommandMap {");
        foreach (var endpoint in BridgeRegistry.Endpoints.Where(item => item.Kind == BridgeRegistry.Command))
        {
            builder.Append("  ").Append(endpoint.Name).Append(": { args: ").Append(names[endpoint.ArgumentType]);
            builder.Append("; result: ").Append(names[endpoint.ResultType]).AppendLine(" };");
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("export type BridgeQueryName = keyof BridgeQueryMap;");
        builder.AppendLine();
        builder.AppendLine("export type BridgeCommandName = keyof BridgeCommandMap;");
        builder.AppendLine();
        return builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    public static void Write(string path)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, Generate());
    }

    public static bool IsCurrent(string path)
    {
        if (!File.Exists(path))
        {
            return false;
        }

        var current = File.ReadAllText(path).Replace("\r\n", "\n", StringComparison.Ordinal);
        return string.Equals(current, Generate(), StringComparison.Ordinal);
    }

    private static void Enqueue(Type type, Queue<Type> pending, HashSet<Type> seen)
    {
        type = Unwrap(type);
        if (type.IsArray)
        {
            Enqueue(type.GetElementType()!, pending, seen);
            return;
        }

        if (IsDictionary(type))
        {
            Enqueue(type.GetGenericArguments()[1], pending, seen);
            return;
        }

        if (IsSequence(type))
        {
            Enqueue(type.GetGenericArguments()[0], pending, seen);
            return;
        }

        if (IsLeaf(type) || !seen.Add(type))
        {
            return;
        }

        pending.Enqueue(type);
    }

    private static bool IsLeaf(Type type)
    {
        type = Unwrap(type);
        return type == typeof(string) || type == typeof(bool) || type == typeof(DateOnly) || type == typeof(GameDate)
            || IsNumber(type) || IsId(type);
    }

    private static string Render(Type type, Dictionary<Type, string> names)
    {
        type = Unwrap(type);
        if (type == typeof(string) || IsId(type))
        {
            return "string";
        }

        if (type == typeof(bool))
        {
            return "boolean";
        }

        if (type == typeof(DateOnly) || type == typeof(GameDate))
        {
            return "IsoDate";
        }

        if (IsNumber(type))
        {
            return "number";
        }

        if (type.IsArray)
        {
            return ItemList(type.GetElementType()!, names);
        }

        if (IsDictionary(type))
        {
            return "Record<string, " + Item(type.GetGenericArguments()[1], names) + ">";
        }

        if (IsSequence(type))
        {
            return ItemList(type.GetGenericArguments()[0], names);
        }

        if (!names.TryGetValue(type, out var name))
        {
            throw new InvalidOperationException("No TypeScript name for " + (type.FullName ?? type.Name) + ".");
        }

        return name;
    }

    private static bool IsNullable(PropertyInfo property)
    {
        var underlying = Nullable.GetUnderlyingType(property.PropertyType);
        if (underlying is not null)
        {
            return true;
        }

        if (property.PropertyType.IsValueType)
        {
            return false;
        }

        return Nullability.Create(property).ReadState == NullabilityState.Nullable;
    }

    private static string Item(Type type, Dictionary<Type, string> names)
    {
        var underlying = Nullable.GetUnderlyingType(type);
        var rendered = Render(underlying ?? type, names);
        return underlying is null ? rendered : rendered + " | null";
    }

    private static string ItemList(Type type, Dictionary<Type, string> names)
    {
        var rendered = Item(type, names);
        return rendered.Contains(" | ", StringComparison.Ordinal) ? "(" + rendered + ")[]" : rendered + "[]";
    }

    private static Type Unwrap(Type type) => Nullable.GetUnderlyingType(type) ?? type;

    private static IEnumerable<PropertyInfo> Properties(Type type) =>
        type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(property => property.GetMethod is not null && property.GetIndexParameters().Length == 0)
            .Where(property => property.GetCustomAttribute<JsonIgnoreAttribute>() is null)
            .Where(property => (Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType) != typeof(AccessContext))
            .OrderBy(property => property.Name, StringComparer.Ordinal);

    private static IReadOnlyList<Type> Derived(Type type)
    {
        IEnumerable<Type> candidates;
        try
        {
            candidates = type.Assembly.GetTypes();
        }
        catch (ReflectionTypeLoadException ex)
        {
            candidates = ex.Types.Where(item => item is not null)!;
        }

        return candidates
            .Where(item => item is not null && item != type && !item.IsAbstract && type.IsAssignableFrom(item))
            .OrderBy(item => item!.FullName, StringComparer.Ordinal)
            .ToArray()!;
    }

    private static Dictionary<Type, string> Names(IEnumerable<Type> types)
    {
        var list = types.ToArray();
        var used = new HashSet<string>(StringComparer.Ordinal);
        var names = new Dictionary<Type, string>();
        foreach (var type in list.OrderBy(type => type.FullName, StringComparer.Ordinal))
        {
            var name = type.IsNested ? NestedName(type) : type.Name;
            if (!used.Add(name))
            {
                name = (type.Namespace ?? "Type").Replace(".", "", StringComparison.Ordinal) + name;
            }

            names[type] = name;
        }

        return names;
    }

    private static string NestedName(Type type)
    {
        var parts = new Stack<string>();
        for (var current = type; current is not null; current = current.DeclaringType)
        {
            parts.Push(current.Name);
        }

        return string.Concat(parts);
    }

    private static bool IsNumber(Type type) =>
        type == typeof(byte) || type == typeof(short) || type == typeof(int) || type == typeof(long)
        || type == typeof(sbyte) || type == typeof(ushort) || type == typeof(uint) || type == typeof(ulong)
        || type == typeof(double) || type == typeof(float) || type == typeof(decimal);

    private static bool IsId(Type type)
    {
        var value = type.GetProperty("Value", BindingFlags.Instance | BindingFlags.Public);
        var assigned = type.GetProperty("IsAssigned", BindingFlags.Instance | BindingFlags.Public);
        return type.Name.EndsWith("Id", StringComparison.Ordinal)
            && value?.PropertyType == typeof(string)
            && assigned?.PropertyType == typeof(bool);
    }

    private static bool IsDictionary(Type type)
    {
        if (!type.IsGenericType || type.GetGenericArguments()[0] != typeof(string))
        {
            return false;
        }

        var definition = type.GetGenericTypeDefinition();
        return definition == typeof(IReadOnlyDictionary<,>)
            || definition == typeof(IDictionary<,>)
            || definition == typeof(Dictionary<,>);
    }

    private static bool IsSequence(Type type)
    {
        if (type == typeof(string) || !type.IsGenericType)
        {
            return false;
        }

        var definition = type.GetGenericTypeDefinition();
        return definition == typeof(IReadOnlyList<>) || definition == typeof(IList<>) || definition == typeof(List<>)
            || definition == typeof(IEnumerable<>);
    }

    private static string Camel(string name) =>
        char.ToLowerInvariant(name[0]) + name[1..];

    private static string PropertyName(string name) =>
        Reserved.Contains(name) ? "\"" + name + "\"" : name;

    private static readonly HashSet<string> Reserved = new(StringComparer.Ordinal)
    {
        "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else",
        "enum", "export", "extends", "false", "finally", "for", "function", "if", "import", "in", "instanceof",
        "new", "null", "return", "super", "switch", "this", "throw", "true", "try", "typeof", "var", "void",
        "while", "with", "protected", "private", "public", "implements", "interface", "let", "package", "yield",
        "static", "any", "boolean", "number", "string", "symbol", "type", "undefined", "never", "unknown",
        "object", "bigint", "override", "readonly", "abstract", "as", "asserts", "async", "await", "constructor",
        "declare", "from", "get", "infer", "is", "keyof", "module", "namespace", "of", "require", "satisfies",
        "set", "unique",
    };
}
